import type { Airport } from "@/lib/types";

/**
 * Major international hubs rendered as distinct icons on the globe.
 * Static dataset — airports don't move, so this ships with the bundle
 * instead of costing an API call.
 */
export const AIRPORTS: Airport[] = [
  { iata: "ATL", name: "Hartsfield–Jackson Atlanta Intl", city: "Atlanta", country: "United States", latitude: 33.64, longitude: -84.43 },
  { iata: "LAX", name: "Los Angeles Intl", city: "Los Angeles", country: "United States", latitude: 33.94, longitude: -118.41 },
  { iata: "ORD", name: "O'Hare Intl", city: "Chicago", country: "United States", latitude: 41.97, longitude: -87.9 },
  { iata: "DFW", name: "Dallas/Fort Worth Intl", city: "Dallas", country: "United States", latitude: 32.9, longitude: -97.04 },
  { iata: "DEN", name: "Denver Intl", city: "Denver", country: "United States", latitude: 39.86, longitude: -104.67 },
  { iata: "JFK", name: "John F. Kennedy Intl", city: "New York", country: "United States", latitude: 40.64, longitude: -73.78 },
  { iata: "SFO", name: "San Francisco Intl", city: "San Francisco", country: "United States", latitude: 37.62, longitude: -122.38 },
  { iata: "SEA", name: "Seattle–Tacoma Intl", city: "Seattle", country: "United States", latitude: 47.45, longitude: -122.31 },
  { iata: "MIA", name: "Miami Intl", city: "Miami", country: "United States", latitude: 25.79, longitude: -80.29 },
  { iata: "ANC", name: "Ted Stevens Anchorage Intl", city: "Anchorage", country: "United States", latitude: 61.17, longitude: -149.99 },
  { iata: "HNL", name: "Daniel K. Inouye Intl", city: "Honolulu", country: "United States", latitude: 21.32, longitude: -157.92 },
  { iata: "YYZ", name: "Toronto Pearson Intl", city: "Toronto", country: "Canada", latitude: 43.68, longitude: -79.63 },
  { iata: "YVR", name: "Vancouver Intl", city: "Vancouver", country: "Canada", latitude: 49.19, longitude: -123.18 },
  { iata: "MEX", name: "Mexico City Intl", city: "Mexico City", country: "Mexico", latitude: 19.44, longitude: -99.07 },
  { iata: "GRU", name: "São Paulo–Guarulhos Intl", city: "São Paulo", country: "Brazil", latitude: -23.44, longitude: -46.47 },
  { iata: "GIG", name: "Rio de Janeiro–Galeão Intl", city: "Rio de Janeiro", country: "Brazil", latitude: -22.81, longitude: -43.25 },
  { iata: "EZE", name: "Ministro Pistarini Intl", city: "Buenos Aires", country: "Argentina", latitude: -34.82, longitude: -58.54 },
  { iata: "SCL", name: "Arturo Merino Benítez Intl", city: "Santiago", country: "Chile", latitude: -33.39, longitude: -70.79 },
  { iata: "BOG", name: "El Dorado Intl", city: "Bogotá", country: "Colombia", latitude: 4.7, longitude: -74.15 },
  { iata: "LIM", name: "Jorge Chávez Intl", city: "Lima", country: "Peru", latitude: -12.02, longitude: -77.11 },
  { iata: "LHR", name: "London Heathrow", city: "London", country: "United Kingdom", latitude: 51.47, longitude: -0.45 },
  { iata: "CDG", name: "Paris Charles de Gaulle", city: "Paris", country: "France", latitude: 49.01, longitude: 2.55 },
  { iata: "FRA", name: "Frankfurt am Main", city: "Frankfurt", country: "Germany", latitude: 50.04, longitude: 8.57 },
  { iata: "MUC", name: "Munich Intl", city: "Munich", country: "Germany", latitude: 48.35, longitude: 11.79 },
  { iata: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam", country: "Netherlands", latitude: 52.31, longitude: 4.76 },
  { iata: "MAD", name: "Adolfo Suárez Madrid–Barajas", city: "Madrid", country: "Spain", latitude: 40.47, longitude: -3.57 },
  { iata: "BCN", name: "Barcelona–El Prat", city: "Barcelona", country: "Spain", latitude: 41.3, longitude: 2.08 },
  { iata: "FCO", name: "Rome Fiumicino", city: "Rome", country: "Italy", latitude: 41.8, longitude: 12.25 },
  { iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland", latitude: 47.46, longitude: 8.55 },
  { iata: "VIE", name: "Vienna Intl", city: "Vienna", country: "Austria", latitude: 48.11, longitude: 16.57 },
  { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium", latitude: 50.9, longitude: 4.48 },
  { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland", latitude: 53.43, longitude: -6.24 },
  { iata: "LIS", name: "Humberto Delgado Lisbon", city: "Lisbon", country: "Portugal", latitude: 38.77, longitude: -9.13 },
  { iata: "CPH", name: "Copenhagen Kastrup", city: "Copenhagen", country: "Denmark", latitude: 55.62, longitude: 12.65 },
  { iata: "ARN", name: "Stockholm Arlanda", city: "Stockholm", country: "Sweden", latitude: 59.65, longitude: 17.92 },
  { iata: "OSL", name: "Oslo Gardermoen", city: "Oslo", country: "Norway", latitude: 60.19, longitude: 11.1 },
  { iata: "HEL", name: "Helsinki–Vantaa", city: "Helsinki", country: "Finland", latitude: 60.32, longitude: 24.96 },
  { iata: "WAW", name: "Warsaw Chopin", city: "Warsaw", country: "Poland", latitude: 52.17, longitude: 20.97 },
  { iata: "PRG", name: "Václav Havel Prague", city: "Prague", country: "Czechia", latitude: 50.1, longitude: 14.26 },
  { iata: "ATH", name: "Athens Intl", city: "Athens", country: "Greece", latitude: 37.94, longitude: 23.94 },
  { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Türkiye", latitude: 41.28, longitude: 28.75 },
  { iata: "SVO", name: "Sheremetyevo Intl", city: "Moscow", country: "Russia", latitude: 55.97, longitude: 37.41 },
  { iata: "TLV", name: "Ben Gurion Intl", city: "Tel Aviv", country: "Israel", latitude: 32.01, longitude: 34.89 },
  { iata: "DXB", name: "Dubai Intl", city: "Dubai", country: "United Arab Emirates", latitude: 25.25, longitude: 55.36 },
  { iata: "AUH", name: "Zayed Intl", city: "Abu Dhabi", country: "United Arab Emirates", latitude: 24.44, longitude: 54.65 },
  { iata: "DOH", name: "Hamad Intl", city: "Doha", country: "Qatar", latitude: 25.27, longitude: 51.61 },
  { iata: "RUH", name: "King Khalid Intl", city: "Riyadh", country: "Saudi Arabia", latitude: 24.96, longitude: 46.7 },
  { iata: "JED", name: "King Abdulaziz Intl", city: "Jeddah", country: "Saudi Arabia", latitude: 21.68, longitude: 39.16 },
  { iata: "CAI", name: "Cairo Intl", city: "Cairo", country: "Egypt", latitude: 30.12, longitude: 31.41 },
  { iata: "LOS", name: "Murtala Muhammed Intl", city: "Lagos", country: "Nigeria", latitude: 6.58, longitude: 3.32 },
  { iata: "NBO", name: "Jomo Kenyatta Intl", city: "Nairobi", country: "Kenya", latitude: -1.32, longitude: 36.93 },
  { iata: "JNB", name: "O. R. Tambo Intl", city: "Johannesburg", country: "South Africa", latitude: -26.14, longitude: 28.25 },
  { iata: "DEL", name: "Indira Gandhi Intl", city: "Delhi", country: "India", latitude: 28.56, longitude: 77.1 },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj Intl", city: "Mumbai", country: "India", latitude: 19.09, longitude: 72.87 },
  { iata: "SIN", name: "Singapore Changi", city: "Singapore", country: "Singapore", latitude: 1.36, longitude: 103.99 },
  { iata: "BKK", name: "Suvarnabhumi", city: "Bangkok", country: "Thailand", latitude: 13.69, longitude: 100.75 },
  { iata: "KUL", name: "Kuala Lumpur Intl", city: "Kuala Lumpur", country: "Malaysia", latitude: 2.75, longitude: 101.71 },
  { iata: "CGK", name: "Soekarno–Hatta Intl", city: "Jakarta", country: "Indonesia", latitude: -6.13, longitude: 106.66 },
  { iata: "HKG", name: "Hong Kong Intl", city: "Hong Kong", country: "Hong Kong", latitude: 22.31, longitude: 113.91 },
  { iata: "PVG", name: "Shanghai Pudong Intl", city: "Shanghai", country: "China", latitude: 31.14, longitude: 121.81 },
  { iata: "PEK", name: "Beijing Capital Intl", city: "Beijing", country: "China", latitude: 40.08, longitude: 116.58 },
  { iata: "CAN", name: "Guangzhou Baiyun Intl", city: "Guangzhou", country: "China", latitude: 23.39, longitude: 113.3 },
  { iata: "ICN", name: "Incheon Intl", city: "Seoul", country: "South Korea", latitude: 37.46, longitude: 126.44 },
  { iata: "HND", name: "Tokyo Haneda", city: "Tokyo", country: "Japan", latitude: 35.55, longitude: 139.78 },
  { iata: "NRT", name: "Narita Intl", city: "Tokyo", country: "Japan", latitude: 35.76, longitude: 140.39 },
  { iata: "SYD", name: "Sydney Kingsford Smith", city: "Sydney", country: "Australia", latitude: -33.95, longitude: 151.18 },
  { iata: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia", latitude: -37.67, longitude: 144.84 },
  { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand", latitude: -37.01, longitude: 174.79 },
];
